DROP TABLE IF EXISTS menu CASCADE;
CREATE TABLE menu (
  id SERIAL PRIMARY KEY NOT NULL,
  food_id INTEGER NOT NULL REFERENCES foods(id) ON DELETE CASCADE,
  category_id INTEGER NOT NULL REFERENCES categories(id) ON DELETE CASCADE
);
